CREATE TABLE IF NOT EXISTS cycles (id INTEGER PRIMARY KEY, home TEXT NOT NULL, records TEXT NOT NULL, bytes INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS control (id INTEGER PRIMARY KEY CHECK(id=1), lease_until INTEGER NOT NULL DEFAULT 0, last_started INTEGER NOT NULL DEFAULT 0, last_error TEXT, total_bytes INTEGER NOT NULL DEFAULT 0);
INSERT OR IGNORE INTO control(id) VALUES(1);
