/* Full platform integration. Views only; no execution or ledger-write requests. */
(function () {
 'use strict';
 const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
 const H=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const N=(x,d=4)=>Number.isFinite(x)?x.toLocaleString('en-US',{maximumFractionDigits:d}):'—';
 const T=x=>Number.isFinite(x)?new Date(x).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false}):'—';
 const P=()=>window.FOXY_RUNTIME_BRIDGE?.getPortfolio?.();
 const empty=()=>'<div class="up-panel"><h3>正式帳本尚未取得</h3><p class="up-desc">等待模擬引擎回應。持倉與資金顯示為無資料。</p><button class="up-btn" data-runtime-refresh>重新讀取</button></div>';
 const tag=s=>'<span class="up-tag">'+H(s)+'</span>';
 const kpi=(name,value)=>'<div class="up-kpi"><span>'+H(name)+'</span><b>'+value+'</b></div>';
 const source=p=>'<p class="up-desc">正式模擬帳本 · '+T(p.served_at)+' · '+N(p.ledger_events,0)+' 筆事件 · 唯讀</p>';
 const state={query:'',limit:12,eventLimit:20,trade:'positions',journal:'performance',market:'crypto',note:null,details:new Set()};
 const action=(label,view,tab='',primary=false)=>`<button class="up-btn ${primary?'primary':''}" data-view="${view}" data-tab="${tab}">${H(label)}</button>`;
 const symbol=s=>`<button class="up-btn fx-symbol" data-runtime-symbol="${H(s)}">${H(s)}</button>`;
 const side=s=>s==='LONG'?'多單':s==='SHORT'?'空單':H(s);
 const fold=(key,title,body)=>`<details class="fx-details" data-detail="${H(key)}" ${state.details.has(key)?'open':''}><summary>${H(title)}</summary><div class="fx-detail-body">${body}</div></details>`;
 const panel=(title,body,tools='')=>`<div class="up-panel"><div class="up-head"><h3>${H(title)}</h3>${tools}</div>${body}</div>`;
 const fresh=t=>Number.isFinite(t.last_ms)&&Date.now()-t.last_ms<180000;
 function warnings(p){
  const s=window.FOXY_RUNTIME_BRIDGE?.getStatus?.(),alerts=[];
  if(!s?.ok||!s.last_cycle||Date.now()-s.last_cycle.time_ms>=180000)alerts.push('引擎連線或更新時間尚未確認，請勿將舊快照視為即時資料。');
  if(s?.ledger_integrity===false)alerts.push('帳本完整性檢查未通過。');
  if(s&&(s.paper_only!==true||s.real_order_lock!==true))alerts.push('交易安全鎖未確認，請檢查設定。');
  const overdue=p?.pending.filter(t=>t.overdue).length;
  if(overdue)alerts.push(`${overdue} 筆等待單已逾期，待引擎處理；不回填成交。`);
  if(p?.diagnostics?.execution_anomalies_24h)alerts.push(`近 24 小時 ${p.diagnostics.execution_anomalies_24h} 筆執行異常，請查看事件帳。`);
  return alerts.length?`<aside class="fx-alert" role="status"><b>需要留意</b>${alerts.map(x=>'<p>'+H(x)+'</p>').join('')}<div class="up-actions">${overdue?action('查看等待單','trade','pending'):''}${action('查看連線','settings')}${action('查看事件','journal','trades')}</div></aside>`:'';
 }
 function homeHTML(){
  const p=P(),s=window.FOXY_RUNTIME_BRIDGE?.getStatus?.();
  const header=`<div class="fx-page-head"><div><p class="eyebrow">FOXYYA / OVERVIEW</p><h1>交易總覽</h1></div>${tag(s?.paper_only===true&&s?.real_order_lock===true?'模擬模式 · 實單已鎖定':'安全狀態待確認')}</div>`;
  if(!p)return header+warnings(p)+empty();
  const b=p.books['5x'],ps=Object.values(b.positions);
  return header+warnings(p)+`<div class="fx-overview-grid">${panel('市場方向',`<div class="fx-lead">${H(p.latest_scan?.regime||'尚無掃描')}</div><p class="fx-meta">最近掃描 ${T(p.latest_scan?.time_ms)}</p>${action('查看市場','market','crypto')}`)}${panel('目前持倉',`<div class="fx-lead">${ps.length}<small> 筆</small></div><p class="fx-meta">5x 主帳 · ${p.pending.length} 筆等待單</p>${action('查看持倉','trade','positions',true)}`)}${panel('主帳權益估值',`<div class="fx-lead">${N(b.equity,2)}<small> USDT</small></div><p class="fx-meta">帳本最後標記價${ps.some(t=>!fresh(t))?' · 標記延遲':''}</p>${action('查看績效','journal','performance')}`)}</div>`+panel('訊號與操作',`<div class="up-actions">${action('查看候選訊號','trade','candidates',true)}${action('開啟圖表','chart')}${action('新聞與事件','market','news')}</div><p class="up-desc">候選排名不代表合格或成交；模擬引擎依原規則處理交易。</p>`)+source(p);
 }
 function renderHome(){const root=$('#focusOverview');if(root)root.innerHTML=homeHTML();}
 function positionsHTML(){const p=P();if(!p)return empty();const rows=Object.values(p.books['5x'].positions);return panel('持倉 · 5x 主帳',source(p)+(rows.length?'<div class="fx-card-list">'+rows.map(t=>`<article class="fx-trade"><div class="up-head"><div>${symbol(t.symbol)} ${tag(side(t.side)+' · '+t.family)}</div><div class="fx-pnl"><span>未實現損益</span><b>${fresh(t)?N((t.side==='LONG'?1:-1)*t.qty*(t.mark-t.entry_fill),2)+' USDT':'—'}</b></div></div>${!fresh(t)?'<p class="up-warn">標記價延遲，暫不顯示即時損益。</p>':''}<div class="fx-inline-metrics"><span>進場 <b>${N(t.entry_fill,8)}</b></span><span>停損 <b>${N(t.stop,8)}</b></span></div>${fold('position-'+t.position_id,'數量、風險與時間',`<div class="fx-inline-metrics"><span>剩餘數量 <b>${N(t.qty,8)}</b></span><span>計畫風險 <b>${N(t.planned_risk_usdt)} USDT</b></span><span>最後標記 <b>${N(t.mark,8)}</b></span></div><p class="fx-meta">進場 ${T(t.entry_ms)}<br>標記 ${T(t.last_ms)}</p>`)}</article>`).join('')+'</div>':'<div class="empty">目前沒有開放中的模擬持倉。</div>'),action('查看等待單','trade','pending'));};
 function pendingHTML(){const p=P();if(!p)return empty();return panel('等待單',source(p)+(p.pending.length?'<div class="fx-card-list">'+p.pending.map(t=>`<article class="fx-trade"><div class="up-head"><div>${symbol(t.symbol)} ${tag(side(t.side)+' · '+t.family)}</div>${tag(t.overdue?'已逾期，待引擎處理':'等待合法開盤')}</div><p class="up-desc">預定開盤 ${T(t.scheduled_open_ms)}</p>${t.overdue?'<p class="up-warn">已錯過預定時間；不回填成交。</p>':''}${fold('pending-'+t.intent_id,'停損與驗證紀錄',`<p>停損 ${N(t.stop,8)}</p><p class="up-desc">${t.latest_revalidation?((t.latest_revalidation.valid===true?'驗證通過':t.latest_revalidation.valid===false?'驗證未通過':'驗證狀態未提供')+' · '+T(t.latest_revalidation.observed_ms)):'等待驗證'}</p>`)}</article>`).join('')+'</div>':'<div class="empty">目前沒有待成交意圖。</div>')+'<p class="up-desc">失效條件由引擎取消；本頁只讀取狀態。</p>');};
 function candidatesHTML(scope='trade'){const p=P();if(!p)return empty();return panel('候選訊號',`<p class="up-desc">排名不代表合格或成交 · 掃描 ${T(p.latest_scan?.time_ms)}</p><label class="up-label" for="${scope}RuntimeSearch">搜尋幣種</label><input class="up-input" id="${scope}RuntimeSearch" data-runtime-search value="${H(state.query)}" placeholder="輸入 BTC、ETH…"><div id="${scope}RuntimeCandidates" data-runtime-candidates></div>`,`<button class="up-btn" data-runtime-refresh>更新</button>`);};
 function renderCandidates(){const root=$('.screen.active [data-runtime-candidates]')||$('[data-runtime-candidates]');if(!root)return;const rows=(P()?.candidates||[]).filter(c=>c.symbol.toUpperCase().includes(state.query.trim().toUpperCase())).sort((a,b)=>a.rank-b.rank);root.innerHTML=rows.length?`<p class="fx-meta">顯示 ${Math.min(rows.length,state.limit)} / ${rows.length} 筆</p><div class="fx-candidates">${rows.slice(0,state.limit).map(c=>`<article class="fx-trade"><div class="up-head">${symbol(c.symbol)}${tag(side(c.side))}</div><div class="fx-inline-metrics"><span>排名 <b>${N(c.rank,0)}</b></span><span>分數 <b>${N(c.score,2)}</b></span><span>${H(c.status)}</span></div>${fold('candidate-'+c.symbol+'-'+c.side,'狀態原因',`<p>${H(c.reason||'未提供原因')}</p>`)}</article>`).join('')}</div>${rows.length>state.limit?'<button class="up-btn fx-more" data-runtime-more="candidates">再顯示 12 筆</button>':''}${state.limit>12?'<button class="up-btn" data-runtime-less>收回前 12 筆</button>':''}`:'<div class="empty">沒有符合的候選資料。</div>';};
 function portfolioHTML(){const p=P();if(!p)return empty();return panel('模擬帳戶比較',source(p)+`<div class="fx-overview-grid">${Object.entries(p.books).map(([name,b])=>`<article class="fx-trade"><h3>${H(name)}</h3><div class="fx-lead">${N(b.equity,2)}<small> USDT</small></div><p class="fx-meta">權益估值 · 最後標記價</p><div class="fx-inline-metrics"><span>餘額 <b>${N(b.balance,2)}</b></span><span>保證金 <b>${N(b.margin_usage_usdt,2)}</b></span><span>持倉 <b>${Object.keys(b.positions).length}</b></span></div></article>`).join('')}</div>`+fold('book-rules','比較口徑','<p>同筆交易沿用相同數量，槓桿只影響保證金。各帳戶僅納入通過模型檢查的部位；強平安全尚未驗證。</p>'));};
 function performanceHTML(){const p=P();if(!p)return empty();const lab=window.FOXY_V11.computeStrategyLab().overall,b=p.books['5x'];return panel('績效摘要',source(p)+'<div class="up-kpis">'+kpi('已入帳淨變動',N(b.balance-p.initial_nav_usdt,2)+' USDT')+kpi('主帳權益估值',N(b.equity,2)+' USDT')+kpi('完整出場交易',N(lab.trades,0))+kpi('平均淨期望 R',N(lab.expectancy,3))+'</div><p class="up-desc">'+(lab.trades<20?'樣本不足：先累積完整交易，不據此升級策略。':'僅描述已出場樣本，不代表策略已驗證。')+'</p><div class="up-actions">'+action('策略分析','journal','lab')+action('事件帳','journal','trades')+action('歷史核對','journal','audit')+'</div>'+fold('performance-rules','績效計算口徑','<p>淨變動含帳本已記錄費用與 Funding。完整出場後才納入勝率與期望值；未實現損益不算已實現績效。</p>'));}
 function eventHTML(){const p=P();if(!p)return empty();return panel('交易事件帳',source(p)+`<p class="fx-meta">顯示最近 ${Math.min(state.eventLimit,p.events.length)} / ${p.events.length} 筆生命週期事件；逐輪標記與重複驗證省略。</p>`+(p.events.length?'<div class="fx-card-list">'+p.events.slice().reverse().slice(0,state.eventLimit).map(e=>{const t=p.trades.find(t=>t.position_id===e.position_id);return `<article class="fx-event"><b>${H(e.symbol||t?.symbol||'—')}</b> ${tag(e.kind)}<p class="up-desc">${H(e.reason||e.status||'—')}</p><p class="fx-meta">${T(e.observed_ms??e.time_ms??e.persisted_ms??e.decision_persist_ms??e.fill_ms)}</p></article>`}).join('')+'</div>':'<div class="empty">目前沒有交易生命週期事件。</div>')+(p.events.length>state.eventLimit?'<button class="up-btn fx-more" data-runtime-more="events">再顯示 20 筆</button>':''),'<button class="up-btn" data-runtime-export>匯出快照</button>');};
 function riskHTML(){const p=P();if(!p)return empty();const risk=Object.values(p.books['5x'].positions).reduce((a,t)=>a+t.planned_risk_usdt,0);return panel('風控概覽','<div class="up-kpis">'+kpi('持倉計畫風險',N(risk)+' USDT')+kpi('意圖與持倉預留',N(p.reserved_risk_fraction*100,2)+'%')+kpi('組合風險上限','1.50%')+kpi('策略控制組','30 天凍結')+'</div>'+fold('risk-rules','完整風控規則','<p>A 0.50% · B 0.35% · C Starter 0.20–0.25% · D 0.35–0.50%。數量與風險由後端計算，前端無修改權限。計畫風險不是最大損失保證。</p><p class="up-desc">PAPER ONLY · REAL ORDER LOCK · Fully Closed Bar · No Backfill</p>'));};
 function reviewHTML(){const p=P();if(!p)return empty();return panel('逐筆覆盤',source(p)+(p.trades.length?p.trades.map(t=>fold('review-'+t.position_id,t.symbol+' · '+side(t.side)+' · '+(t.closed?'已結束':'持倉中'),'<div class="up-kpis">'+kpi('淨損益',N(t.net_pnl_usdt)+' USDT')+kpi('已實現淨 R',t.closed?N(t.realized_r,3):'未完結')+kpi('MFE / MAE（取樣）',t.mark_samples?N(t.mfe_r,3)+' / '+N(t.mae_r,3):'無資料')+kpi('費用 / Funding',N(t.fees_usdt)+' / '+N(t.funding_usdt))+'</div>')).join(''):'<div class="empty">目前尚無正式模擬交易。</div>')+'<p class="up-desc">MFE／MAE 來自帳本標記價取樣，可能漏掉取樣間極值。</p><label class="up-label" for="runtimeNote">本機覆盤筆記（不修改帳本）</label><textarea class="up-input" id="runtimeNote" rows="4"></textarea><button class="up-btn" id="runtimeSaveNote">保存筆記</button><span id="runtimeNoteStatus" role="status"></span>');}
 const oldJournal=journalSub,oldGo=go,oldMarket=renderMarket;
 tradeSub=function(sub){state.trade=sub;const el=$('#tradeSubContent');if(!el)return;el.innerHTML=sub==='positions'?positionsHTML():sub==='pending'?pendingHTML():sub==='books'?portfolioHTML():sub==='ledger'?eventHTML():sub==='risk'||sub==='intelligence'?riskHTML():candidatesHTML();renderCandidates()};
 journalSub=function(sub){state.journal=sub;if(sub==='audit'){oldJournal(sub);return}const el=$('#journalSubContent');if(!el)return;el.innerHTML=!P()?empty():sub==='performance'?performanceHTML():sub==='lab'?window.FOXY_V11.strategyLabHTML():sub==='review'?reviewHTML():eventHTML();const note=$('#runtimeNote');if(note){if(state.note===null){try{state.note=localStorage.getItem('foxyya.runtime.review.v1')||''}catch{state.note=''}}note.value=state.note;$('#runtimeSaveNote').onclick=()=>{try{localStorage.setItem('foxyya.runtime.review.v1',note.value);$('#runtimeNoteStatus').textContent='已保存至這個瀏覽器'}catch{$('#runtimeNoteStatus').textContent='保存失敗，請複製筆記'}}}};
 renderMarket=function(m){if(document.activeElement?.hasAttribute?.('data-runtime-search')&&m==='crypto')return;state.market=m;const root=$('#marketMainContent'),intel=window.FOXY_V11;if(!root)return;if(m==='crypto'){root.innerHTML=candidatesHTML('market');renderCandidates()}else if(m==='watch')oldMarket('crypto');else if(m==='rotation')root.innerHTML=panel('市場廣度與資金輪動',intel.rotationHTML());else if(m==='news')root.innerHTML=intel.upcomingEventsHTML()+fold('news-feed','展開新聞',intel.newsHTML());else if(m==='deriv')root.innerHTML=intel.crowdingHTML();else if(m==='read')root.innerHTML=intel.marketReadHTML()+fold('source-confidence','來源與新鮮度',intel.confidenceHTML());else if(m==='engine'){state.trade='candidates';go('trade')}else oldMarket(m);};
 go=function(id){const tab=state[id];oldGo(id);if(tab)state[id]=tab;if(id==='overview')renderHome();if(id==='settings')settings();if(id==='trade'){selectTab('#tradeTabs',state.trade);tradeSub(state.trade)}if(id==='journal'){selectTab('#journalTabs',state.journal);journalSub(state.journal)}if(id==='market'){selectTab('#marketTabs',state.market);renderMarket(state.market)}};
 function settings(){const root=$('#upgradeSettings');if(!root)return;const p=P(),s=window.FOXY_RUNTIME_BRIDGE?.getStatus?.();root.innerHTML=panel('連線與安全','<div class="up-kpis">'+kpi('引擎',s?.ok&&s.last_cycle&&Date.now()-s.last_cycle.time_ms<180000?'已連線':'待確認')+kpi('實單安全鎖',s?.real_order_lock===true?'已鎖定':'待確認')+kpi('帳本完整性',s?.ledger_integrity===true?'通過':s?.ledger_integrity===false?'未通過':'待確認')+'</div><button class="up-btn" data-runtime-refresh>重新讀取</button>'+fold('connection-tech','技術資訊','<p>策略 '+H(s?.strategy_version||'—')+'</p><p>引擎循環 '+N(s?.cycle_count,0)+' · 帳本事件 '+N(s?.ledger_events,0)+'</p><p class="up-desc">引擎在伺服器運行，關閉瀏覽器不會停止。'+H(s?.last_error?.message||'')+'</p>'))+riskHTML();const worker=$('#paperWorkerUrl');if(worker){worker.value=location.origin;worker.readOnly=true;worker.previousElementSibling.textContent='正式模擬引擎';worker.nextElementSibling.textContent='與平台同一網址；不使用舊版 Worker/D1 帳本。'}const nav=all('#settings .setting').find(x=>x.textContent.includes('Forward Paper NAV'))?.querySelector('input');if(nav)nav.value=p?N(p.books['5x'].equity):'UNAVAILABLE';}

 function selectTab(root,key){all(root+' button').forEach(b=>{const active=(b.dataset.sub||b.dataset.market)===key;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}
 function renderCurrent(){renderHome();if(document.activeElement?.hasAttribute?.('data-runtime-search'))return;if($('#trade')?.classList.contains('active'))tradeSub(state.trade);if($('#market')?.classList.contains('active')&&!['us','tw','macro','watch'].includes(state.market))renderMarket(state.market);if($('#journal')?.classList.contains('active')&&!['review','audit'].includes(state.journal))journalSub(state.journal);if($('#settings')?.classList.contains('active'))settings()}
 function bindTabs(root,fn,key='sub'){const el=$(root);if(!el)return;el.addEventListener('click',e=>{const b=e.target.closest('button[data-'+key+']');if(!b)return;e.preventDefault();e.stopImmediatePropagation();selectTab(root,b.dataset[key]);fn(b.dataset[key])},true)}
 function tabs(root,items,key='sub'){const el=$(root);if(el)el.innerHTML=items.map(([id,label],i)=>`<button class="subtab ${i===0?'active':''}" data-${key}="${id}" aria-pressed="${i===0}">${label}</button>`).join('')}
 function boot(){
  // The production service has no legacy Worker/D1 login or book-switch API.
  $('#runtimeSettings')?.remove();
  $('#v11CapitalOS')?.remove();
  const home=$('#overview');if(home&&!$('#focusOverview'))home.insertAdjacentHTML('afterbegin','<div id="focusOverview"></div>');
  document.body.classList.add('fx-focus');
  tabs('#tradeTabs',[['positions','持倉'],['pending','等待單'],['candidates','候選'],['books','帳戶比較'],['risk','風控']]);
  tabs('#journalTabs',[['performance','績效'],['lab','策略分析'],['trades','事件帳'],['review','覆盤'],['audit','歷史核對']]);
  tabs('#marketTabs',[['crypto','多空排行'],['watch','自選與掃描'],['read','市場解讀'],['rotation','資金輪動'],['news','新聞事件'],['deriv','衍生品'],['us','美股'],['tw','台股'],['macro','宏觀']],'market');
  [['market','市場觀察'],['trade','交易工作台'],['journal','績效與紀錄'],['settings','設定']].forEach(([id,title])=>{const h=$('#'+id+' h1');if(h)h.textContent=title;const sub=$('#'+id+' > .sectionHead .sub');if(sub)sub.hidden=true});
  const grid=$('#settings .settingsGrid');if(grid&&!$('#legacyConnection')){const d=document.createElement('details');d.id='legacyConnection';d.className='fx-details';d.innerHTML='<summary>其他資料來源與參考設定</summary>';grid.before(d);d.appendChild(grid)}
  const build=$('#releaseBuild');if(build)build.textContent='v11.2.2 · PAPER';
  const journal=$('.dock [data-go="journal"]');if(journal)journal.innerHTML='<b>▤</b>績效';
  bindTabs('#tradeTabs',s=>tradeSub(s));bindTabs('#journalTabs',s=>journalSub(s));bindTabs('#marketTabs',s=>renderMarket(s),'market');
  all('.dock button').forEach(b=>b.onclick=()=>go(b.dataset.go));
  document.addEventListener('toggle',e=>{const key=e.target.dataset?.detail;if(key&&e.target.isConnected){if(e.target.open)state.details.add(key);else state.details.delete(key)}},true);
  document.addEventListener('input',e=>{if(e.target.hasAttribute('data-runtime-search')){state.query=e.target.value;state.limit=12;renderCandidates()}if(e.target.id==='runtimeNote')state.note=e.target.value});
  document.addEventListener('click',e=>{
   const route=e.target.closest('[data-view]');if(route){const id=route.dataset.view,tab=route.dataset.tab;if(tab&&['trade','journal','market'].includes(id))state[id]=tab;go(id);if(id==='chart')loadK(S.selected,S.tf)}
   const more=e.target.closest('[data-runtime-more]');if(more){if(more.dataset.runtimeMore==='candidates'){state.limit+=12;renderCandidates()}else{state.eventLimit+=20;journalSub('trades')}}
   if(e.target.closest('[data-runtime-less]')){state.limit=12;renderCandidates();$('.screen.active [data-runtime-search]')?.focus()}
   if(e.target.closest('[data-runtime-refresh]'))window.FOXY_RUNTIME_BRIDGE.refresh();
   const symbol=e.target.closest('[data-runtime-symbol]')?.dataset.runtimeSymbol;
   if(symbol){S.selected=symbol;go('chart');loadK(symbol,'1h')}
   if(e.target.closest('[data-runtime-export]')){const p=P();if(!p)return;const url=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='FOXYYA_runtime_snapshot.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  });
  window.addEventListener('foxy:runtime-update',renderCurrent);
  document.body.dataset.runtimeUi='full-v11.2.2';renderCurrent();
 }
 window.FOXY_RUNTIME_UI=Object.freeze({render:renderCurrent,renderHome,homeHTML,version:'11.2.2'});
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
