'use strict';
const N=require('../data/context_normalizer.js');
const descriptor=Object.freeze({id:'cftc-cot-official',sourceLabel:'CFTC Commitments of Traders TFF Futures Only',markets:['GLOBAL','US'],capabilities:['FLOW','MACRO'],transport:'PUBLIC_READ_ONLY',executionWrite:false,priority:60,serverOnly:true});
const SOURCE='CFTC:TFF:gpe5-46if',EVIDENCE_ROLE='CONFIRMATION',LATENCY_CLASS='WEEKLY';
function numeric(v){if(v===null||v===undefined)return null;if(typeof v==='string'&&!v.trim())return null;const n=Number(String(v).replace(/,/g,''));return Number.isFinite(n)?n:null;}
function dateOnly(v){const s=String(v??'');const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(!m)throw Error('REPORT_DATE_INVALID');const iso=`${m[1]}-${m[2]}-${m[3]}`;const d=new Date(`${iso}T00:00:00Z`);if(d.getUTCFullYear()!==+m[1]||d.getUTCMonth()+1!==+m[2]||d.getUTCDate()!==+m[3])throw Error('REPORT_DATE_INVALID');return iso;}
function obs(entityId,field,value,receivedAt){return N.makeContextObservation({entityId,scope:'GLOBAL',field,value,unit:'CONTRACT',observedAt:receivedAt,receivedAt,source:SOURCE,status:value===null?'UNAVAILABLE':'SNAPSHOT',confidence:value===null?0:1});}
function normalizeTffRow(row,{receivedAt}){
 if(!row||typeof row!=='object')throw Error('ROW_REQUIRED');if(!Number.isFinite(receivedAt)||receivedAt<0)throw Error('RECEIVED_AT_INVALID');
 const reportDate=dateOnly(row.report_date_as_yyyy_mm_dd),code=String(row.cftc_contract_market_code??'').trim();if(!code)throw Error('CONTRACT_CODE_REQUIRED');const entityId=`CFTC:TFF:${code}`;
 const values={openInterest:numeric(row.open_interest_all),assetLong:numeric(row.asset_mgr_positions_long),assetShort:numeric(row.asset_mgr_positions_short),assetSpread:numeric(row.asset_mgr_positions_spread),levLong:numeric(row.lev_money_positions_long),levShort:numeric(row.lev_money_positions_short),levSpread:numeric(row.lev_money_positions_spread),dealerLong:numeric(row.dealer_positions_long_all),dealerShort:numeric(row.dealer_positions_short_all)};
 const net=(a,b)=>a===null||b===null?null:a-b;
 const defs=[['positioning.cot.open_interest',values.openInterest],['positioning.cot.asset_manager.long',values.assetLong],['positioning.cot.asset_manager.short',values.assetShort],['positioning.cot.asset_manager.spread',values.assetSpread],['positioning.cot.asset_manager.net',net(values.assetLong,values.assetShort)],['positioning.cot.leveraged_money.long',values.levLong],['positioning.cot.leveraged_money.short',values.levShort],['positioning.cot.leveraged_money.spread',values.levSpread],['positioning.cot.leveraged_money.net',net(values.levLong,values.levShort)],['positioning.cot.dealer.long',values.dealerLong],['positioning.cot.dealer.short',values.dealerShort],['positioning.cot.dealer.net',net(values.dealerLong,values.dealerShort)]];
 return Object.freeze({entityId,contractCode:code,marketName:String(row.market_and_exchange_names??''),contractMarket:String(row.contract_market_name??''),commodityName:String(row.commodity_name??''),reportDate,knowledgeTime:'RECEIVED_AT',pointInTimeSafe:false,latencyClass:LATENCY_CLASS,evidenceRole:EVIDENCE_ROLE,source:SOURCE,observations:Object.freeze(defs.map(([f,v])=>obs(entityId,f,v,receivedAt)))});
}
function normalize(dataset,payload,context={}){if(dataset==='TFF_ROW')return normalizeTffRow(payload,context);if(dataset==='TFF_ROWS'){if(!Array.isArray(payload))throw Error('ROWS_REQUIRED');return Object.freeze(payload.map(x=>normalizeTffRow(x,context)));}throw Error('DATASET_UNSUPPORTED');}
module.exports=Object.freeze({descriptor,SOURCE,EVIDENCE_ROLE,LATENCY_CLASS,numeric,dateOnly,normalizeTffRow,normalize});
