'use strict';
const N=require('../data/normalizer.js');
const descriptor=Object.freeze({id:'finra-research-official',sourceLabel:'FINRA public equity transparency datasets',markets:['US'],capabilities:['FLOW'],transport:'AUTHENTICATED_READ_ONLY',executionWrite:false,priority:70,serverOnly:true});
const EVIDENCE_ROLE='CONFIRMATION',LATENCY_CLASS='DELAYED';
const REG_SHO_SOURCE='FINRA:regShoDaily',SHORT_INTEREST_SOURCE='FINRA:consolidatedShortInterest';
function numeric(v){if(v===null||v===undefined)return null;if(typeof v==='string'&&!v.trim())return null;const n=Number(String(v).replace(/,/g,''));return Number.isFinite(n)?n:null;}
function isoDate(v){const s=String(v??'');const m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)throw Error('DATE_INVALID');const d=new Date(`${s}T00:00:00Z`);if(d.getUTCFullYear()!==+m[1]||d.getUTCMonth()+1!==+m[2]||d.getUTCDate()!==+m[3])throw Error('DATE_INVALID');return s;}
function resolveInstrument(resolver,symbol,marketCode){if(typeof resolver!=='function')throw Error('INSTRUMENT_RESOLVER_REQUIRED');const i=resolver(String(symbol??'').trim().toUpperCase(),marketCode);if(!i)throw Error('INSTRUMENT_UNRESOLVED');return i;}
function obs(instrument,field,value,unit,receivedAt,source){return N.makeObservation({instrument,field,value,unit,currency:instrument.currency,observedAt:receivedAt,receivedAt,source,status:value===null?'UNAVAILABLE':'SNAPSHOT',confidence:value===null?0:1});}
function normalizeRegShoDaily(rows,{receivedAt,instrumentResolver}){
 if(!Array.isArray(rows))throw Error('ROWS_REQUIRED');if(!Number.isFinite(receivedAt)||receivedAt<0)throw Error('RECEIVED_AT_INVALID');
 const groups=new Map();
 for(const row of rows){const symbol=String(row?.securitiesInformationProcessorSymbolIdentifier??'').trim().toUpperCase();if(!symbol)throw Error('SYMBOL_REQUIRED');const tradeDate=isoDate(row.tradeReportDate);const key=`${symbol}|${tradeDate}`;let g=groups.get(key);if(!g){g={symbol,tradeDate,marketCode:row.marketCode,total:0,short:0,exempt:0,totalComplete:true,shortComplete:true,exemptComplete:true,facilities:new Set()};groups.set(key,g);}const vals=[['total',numeric(row.totalParQuantity),'totalComplete'],['short',numeric(row.shortParQuantity),'shortComplete'],['exempt',numeric(row.shortExemptParQuantity),'exemptComplete']];for(const [k,v,flag] of vals){if(v===null)g[flag]=false;else g[k]+=v;}if(row.reportingFacilityCode)g.facilities.add(String(row.reportingFacilityCode));}
 const out=[];
 for(const g of groups.values()){const instrument=resolveInstrument(instrumentResolver,g.symbol,g.marketCode);const total=g.totalComplete?g.total:null,short=g.shortComplete?g.short:null,exempt=g.exemptComplete?g.exempt:null,ratio=short!==null&&total!==null&&total>0?short/total:null;const observations=[obs(instrument,'flow.finra.short_volume',short,'SHARE',receivedAt,REG_SHO_SOURCE),obs(instrument,'flow.finra.short_exempt_volume',exempt,'SHARE',receivedAt,REG_SHO_SOURCE),obs(instrument,'flow.finra.total_reported_volume',total,'SHARE',receivedAt,REG_SHO_SOURCE),obs(instrument,'flow.finra.short_volume_ratio',ratio,'RATIO',receivedAt,REG_SHO_SOURCE)];out.push(Object.freeze({instrument,tradeDate:g.tradeDate,facilities:Object.freeze([...g.facilities].sort()),knowledgeTime:'RECEIVED_AT',pointInTimeSafe:false,latencyClass:LATENCY_CLASS,evidenceRole:EVIDENCE_ROLE,source:REG_SHO_SOURCE,observations:Object.freeze(observations)}));}
 return Object.freeze(out);
}
function normalizeShortInterestRow(row,{receivedAt,instrumentResolver}){
 if(!row||typeof row!=='object')throw Error('ROW_REQUIRED');if(!Number.isFinite(receivedAt)||receivedAt<0)throw Error('RECEIVED_AT_INVALID');const symbol=String(row.symbolCode??'').trim().toUpperCase();if(!symbol)throw Error('SYMBOL_REQUIRED');const settlementDate=isoDate(row.settlementDate);const instrument=resolveInstrument(instrumentResolver,symbol,row.issuerServicesGroupExchangeCode);const defs=[['flow.finra.short_interest.current',numeric(row.currentShortPositionQuantity),'SHARE'],['flow.finra.short_interest.previous',numeric(row.previousShortPositionQuantity),'SHARE'],['flow.finra.short_interest.change',numeric(row.changePreviousNumber),'SHARE'],['flow.finra.short_interest.change_pct',numeric(row.changePercent),'PERCENT'],['flow.finra.short_interest.average_daily_volume',numeric(row.averageDailyVolumeQuantity),'SHARE'],['flow.finra.short_interest.days_to_cover',numeric(row.daysToCoverQuantity),'DAY']];return Object.freeze({instrument,issueName:String(row.issueName??''),settlementDate,revisionFlag:row.revisionFlag??null,knowledgeTime:'RECEIVED_AT',pointInTimeSafe:false,latencyClass:LATENCY_CLASS,evidenceRole:EVIDENCE_ROLE,source:SHORT_INTEREST_SOURCE,observations:Object.freeze(defs.map(([field,value,unit])=>obs(instrument,field,value,unit,receivedAt,SHORT_INTEREST_SOURCE)))});
}
function normalize(dataset,payload,context={}){if(dataset==='REG_SHO_DAILY')return normalizeRegShoDaily(payload,context);if(dataset==='SHORT_INTEREST')return Array.isArray(payload)?Object.freeze(payload.map(x=>normalizeShortInterestRow(x,context))):normalizeShortInterestRow(payload,context);throw Error('DATASET_UNSUPPORTED');}
module.exports=Object.freeze({descriptor,EVIDENCE_ROLE,LATENCY_CLASS,REG_SHO_SOURCE,SHORT_INTEREST_SOURCE,numeric,normalizeRegShoDaily,normalizeShortInterestRow,normalize});
