const test=require('node:test');
const assert=require('node:assert/strict');
const X=require('../v12/early_trend/evidence_pipeline.js');
const P=require('../v12/early_trend/evidence_policy.js');
const obs=(field,value,{receivedAt=1000,source='official',status='SNAPSHOT',confidence=1}={})=>({field,value,receivedAt,observedAt:receivedAt-10,source,status,confidence});
const twPolicy=P.freezeEvidencePolicy({schemaVersion:'foxyya-evidence-policy/1',id:'tw-v1',market:'TW',mode:'RESEARCH_CONTROL',createdAt:1,researchOnly:true,executionWrite:false,parameters:{institutionalFlow:{fullScaleRatio:0.05},institutionalPersistence:{minSessions:3,fullScaleAverageRatio:0.04},revenueAcceleration:{fullScalePct:20}}});
const jpPolicy=P.freezeEvidencePolicy({schemaVersion:'foxyya-evidence-policy/1',id:'jp-v1',market:'JP',mode:'RESEARCH_CONTROL',createdAt:1,researchOnly:true,executionWrite:false,parameters:{guidanceRevision:{fullScalePct:20}}});
const session=(net,volume,receivedAt)=>({flowObservations:[obs('flow.total_net',net,{receivedAt,source:'TWSE:T86'})],volumeObservation:obs('volume.shares',volume,{receivedAt,source:'TWSE:STOCK_DAY_ALL'})});
const revenue=(period,yoy,receivedAt)=>({instrument:{instrumentId:'TWSE:2330'},reportPeriod:period,knowledgeTime:'RECEIVED_AT',observations:[obs('fundamental.revenue.yoy_pct',yoy,{receivedAt,source:'TWSE:t187ap05_L'})]});
const financial=(sales,receivedAt)=>({instrument:{instrumentId:'TSE:72030'},disclosedAt:receivedAt,pointInTimeSafe:true,observations:[obs('guidance.sales_fy',sales,{receivedAt,source:'JPX:FINS'})]});

test('TW evidence pipeline builds three auditable evidence items from approved policy',()=>{const out=X.buildEvidenceSet({policy:twPolicy,inputs:{instrumentId:'TWSE:2330',currentFlow:session(300,10000,3000),institutionalSessions:[session(200,10000,1000),session(300,10000,2000),session(400,10000,3000)],currentRevenue:revenue('2026-08',20,4000),previousRevenue:revenue('2026-07',8,2000)}});assert.equal(out.policyId,'tw-v1');assert.equal(out.market,'TW');assert.equal(out.researchOnly,true);assert.equal(out.executionWrite,false);assert.equal(out.evidence.length,3);assert.deepEqual(out.evidence.map(x=>x.kind),['INSTITUTIONAL_NET_VOLUME_RATIO','INSTITUTIONAL_PERSISTENCE','MONTHLY_REVENUE_YOY_ACCELERATION']);});
test('pipeline ignores threshold-looking values in input and uses policy only',()=>{const out=X.buildEvidenceSet({policy:twPolicy,inputs:{instrumentId:'TWSE:2330',fullScaleRatio:999,currentFlow:session(300,10000,3000),institutionalSessions:[session(200,10000,1000),session(300,10000,2000),session(400,10000,3000)],currentRevenue:revenue('2026-08',20,4000),previousRevenue:revenue('2026-07',8,2000)}});const flow=out.evidence.find(x=>x.kind==='INSTITUTIONAL_NET_VOLUME_RATIO');assert.equal(flow.metrics.fullScaleRatio,0.05);});
test('JP evidence pipeline emits management guidance revision only',()=>{const out=X.buildEvidenceSet({policy:jpPolicy,inputs:{currentFinancial:financial(110,2000),previousFinancial:financial(100,1000)}});assert.equal(out.market,'JP');assert.equal(out.evidence.length,1);assert.equal(out.evidence[0].kind,'MANAGEMENT_GUIDANCE_REVISION');assert.equal(out.evidence[0].direction,0.5);});
test('pipeline rejects policy/market mismatch rather than silently adapting thresholds',()=>{assert.throws(()=>X.buildEvidenceSet({policy:twPolicy,market:'JP',inputs:{}}),/POLICY_MARKET_MISMATCH/);});
test('shadow policy remains explicitly shadow in evidence set',()=>{const shadow=P.freezeEvidencePolicy({...twPolicy,id:'tw-shadow-v2',mode:'SHADOW'});const out=X.buildEvidenceSet({policy:shadow,inputs:{instrumentId:'TWSE:2330',currentFlow:session(300,10000,3000),institutionalSessions:[],currentRevenue:null,previousRevenue:null}});assert.equal(out.mode,'SHADOW');assert.equal(out.researchOnly,true);assert.equal(out.executionWrite,false);});
