const test=require('node:test');const assert=require('node:assert/strict');
const COT=require('../v12/providers/cftc_cot_adapter.js');
const receivedAt=Date.parse('2026-09-04T20:00:00Z');
const row={id:'13874A_2026-09-01',market_and_exchange_names:'E-MINI S&P 500 - CHICAGO MERCANTILE EXCHANGE',report_date_as_yyyy_mm_dd:'2026-09-01T00:00:00.000',contract_market_name:'CHICAGO MERCANTILE EXCHANGE',cftc_contract_market_code:'13874A',commodity_name:'S&P 500 STOCK INDEX',open_interest_all:'1234567',asset_mgr_positions_long:'700000',asset_mgr_positions_short:'300000',asset_mgr_positions_spread:'10000',lev_money_positions_long:'200000',lev_money_positions_short:'350000',lev_money_positions_spread:'20000',dealer_positions_long_all:'100000',dealer_positions_short_all:'400000'};

test('CFTC provider is weekly read-only confirmation evidence',()=>{assert.equal(COT.descriptor.executionWrite,false);assert.equal(COT.descriptor.serverOnly,true);assert.equal(COT.EVIDENCE_ROLE,'CONFIRMATION');assert.equal(COT.LATENCY_CLASS,'WEEKLY');});
test('CFTC TFF preserves asset manager and leveraged money categories separately',()=>{const r=COT.normalizeTffRow(row,{receivedAt});const f=Object.fromEntries(r.observations.map(x=>[x.field,x.value]));assert.equal(r.reportDate,'2026-09-01');assert.equal(r.knowledgeTime,'RECEIVED_AT');assert.equal(r.pointInTimeSafe,false);assert.equal(f['positioning.cot.asset_manager.long'],700000);assert.equal(f['positioning.cot.asset_manager.short'],300000);assert.equal(f['positioning.cot.asset_manager.net'],400000);assert.equal(f['positioning.cot.leveraged_money.net'],-150000);});
test('CFTC observations use receive time, never Tuesday report date, as knowledge time',()=>{const r=COT.normalizeTffRow(row,{receivedAt});for(const x of r.observations)assert.equal(x.observedAt,receivedAt);});
test('CFTC missing category value is UNAVAILABLE rather than zero',()=>{const r=COT.normalizeTffRow({...row,asset_mgr_positions_long:null},{receivedAt});const x=r.observations.find(x=>x.field==='positioning.cot.asset_manager.long');assert.equal(x.value,null);assert.equal(x.status,'UNAVAILABLE');});
test('CFTC net is unavailable if either long or short is missing',()=>{const r=COT.normalizeTffRow({...row,asset_mgr_positions_short:null},{receivedAt});const x=r.observations.find(x=>x.field==='positioning.cot.asset_manager.net');assert.equal(x.value,null);assert.equal(x.status,'UNAVAILABLE');});
test('CFTC invalid report date is rejected',()=>{assert.throws(()=>COT.normalizeTffRow({...row,report_date_as_yyyy_mm_dd:'bad'},{receivedAt}),/REPORT_DATE_INVALID/);});
