const test=require('node:test');const assert=require('node:assert/strict');
const F=require('../v12/providers/finra_adapter.js');
const receivedAt=Date.parse('2026-09-09T22:00:00Z');
const resolver=(symbol)=>({instrumentId:`NASDAQ:${symbol}`,exchange:'NASDAQ',symbol,market:'US',region:'US',currency:'USD',timezone:'America/New_York',assetType:'EQUITY'});

test('FINRA provider is credentialed server-only delayed confirmation evidence',()=>{assert.equal(F.descriptor.serverOnly,true);assert.equal(F.descriptor.executionWrite,false);assert.equal(F.LATENCY_CLASS,'DELAYED');assert.equal(F.EVIDENCE_ROLE,'CONFIRMATION');});

test('Reg SHO daily rows aggregate facilities before computing symbol totals',()=>{const rows=[{reportingFacilityCode:'NQTRF',totalParQuantity:1000,shortParQuantity:400,shortExemptParQuantity:10,tradeReportDate:'2026-09-08',securitiesInformationProcessorSymbolIdentifier:'NVDA',marketCode:'Q'},{reportingFacilityCode:'NYTRF',totalParQuantity:500,shortParQuantity:100,shortExemptParQuantity:5,tradeReportDate:'2026-09-08',securitiesInformationProcessorSymbolIdentifier:'NVDA',marketCode:'Q'}];const out=F.normalizeRegShoDaily(rows,{receivedAt,instrumentResolver:resolver});assert.equal(out.length,1);const r=out[0],m=Object.fromEntries(r.observations.map(x=>[x.field,x]));assert.equal(r.instrument.instrumentId,'NASDAQ:NVDA');assert.equal(r.tradeDate,'2026-09-08');assert.equal(m['flow.finra.short_volume'].value,500);assert.equal(m['flow.finra.total_reported_volume'].value,1500);assert.equal(m['flow.finra.short_volume_ratio'].value,500/1500);assert.equal(m['flow.finra.short_volume_ratio'].unit,'RATIO');});

test('FINRA Reg SHO uses receive time as knowledge time and never trade date as availability',()=>{const rows=[{totalParQuantity:1000,shortParQuantity:400,shortExemptParQuantity:0,tradeReportDate:'2026-09-08',securitiesInformationProcessorSymbolIdentifier:'NVDA'}];const r=F.normalizeRegShoDaily(rows,{receivedAt,instrumentResolver:resolver})[0];assert.equal(r.knowledgeTime,'RECEIVED_AT');assert.equal(r.pointInTimeSafe,false);assert.ok(r.observations.every(x=>x.observedAt===receivedAt));});

test('Consolidated short interest preserves position quantity and days to cover separately',()=>{const r=F.normalizeShortInterestRow({symbolCode:'NVDA',issueName:'NVIDIA Corp',settlementDate:'2026-08-31',currentShortPositionQuantity:21000000,previousShortPositionQuantity:20000000,changePreviousNumber:1000000,changePercent:5,averageDailyVolumeQuantity:30000000,daysToCoverQuantity:.7},{receivedAt,instrumentResolver:resolver});const m=Object.fromEntries(r.observations.map(x=>[x.field,x.value]));assert.equal(m['flow.finra.short_interest.current'],21000000);assert.equal(m['flow.finra.short_interest.previous'],20000000);assert.equal(m['flow.finra.short_interest.change_pct'],5);assert.equal(m['flow.finra.short_interest.days_to_cover'],.7);});

test('FINRA adapter does not label high short volume as bearish direction',()=>{const r=F.normalizeRegShoDaily([{totalParQuantity:1000,shortParQuantity:900,shortExemptParQuantity:0,tradeReportDate:'2026-09-08',securitiesInformationProcessorSymbolIdentifier:'NVDA'}],{receivedAt,instrumentResolver:resolver})[0];assert.equal(Object.hasOwn(r,'direction'),false);assert.equal(Object.hasOwn(r,'signal'),false);});

test('FINRA requires an instrument resolver instead of guessing exchange from market code',()=>{assert.throws(()=>F.normalizeRegShoDaily([{totalParQuantity:1,shortParQuantity:1,tradeReportDate:'2026-09-08',securitiesInformationProcessorSymbolIdentifier:'NVDA'}],{receivedAt}),/INSTRUMENT_RESOLVER_REQUIRED/);});
