'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('v12/ui/app.js','utf8');const html=fs.readFileSync('v12/ui/index.html','utf8');
function element(dataset={}){return {dataset,hidden:false,disabled:false,attrs:{},textContent:'',innerHTML:'',classList:{toggle(){},add(){},remove(){}},setAttribute(k,v){this.attrs[k]=v},getAttribute(k){return this.attrs[k]},focus(){this.focused=true},scrollIntoView(){},addEventListener(){}}}
function boot({hash='#home',load,pathname='',now=()=>Date.now()}={}){
 const events={},windowEvents={},writes=[];const screens=['HOME','MARKETS','RESEARCH','POSITIONS','RESULTS','LAB','INTELLIGENCE','SYSTEM'].map(x=>element({screen:x}));
 const cards=['US','TW','CRYPTO'].map(x=>element({opportunityMarket:x,filterMarket:x}));
 const health=element(),more=element(),notice=element(),label=element(),refresh=element();more.hidden=true;
 const nodes={'#data-health':health,'#more-sheet':more,'#toast':element(),'#read-status':notice,'#market-scope-label':label,'#refresh-research':refresh};
 const doc={querySelector:s=>nodes[s]||null,querySelectorAll(s){if(s==='[data-screen]')return screens;if(s.includes('data-filter-market')||s.includes('data-opportunity-market'))return cards;return []},addEventListener(k,v){events[k]=v}};
 const location={hash,pathname};const history={replaceState(a,b,url){writes.push({kind:'replace',url});location.hash=url},pushState(a,b,url){writes.push({kind:'push',url});location.hash=url}};
 const window={addEventListener(k,v){windowEvents[k]=v},scrollTo(){},FOXY_V12_HOME_VIEW_MODEL:{buildHomeViewModel:x=>x},FOXY_V12_HOME_RENDERER:{renderHomeSections:x=>x},FOXY_V12_HOME_DOM:{applyHomeRender(){}},FOXY_V12_STAGING_READ_CLIENT:{createHomeReadClient:()=>({load:load||async function(){return {status:'UNAVAILABLE',data:null}}})}};
 vm.runInNewContext(source,{window,document:doc,location,history,URLSearchParams,AbortController,Date:{now},setTimeout(){return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){}},{filename:'app.js'});
 return {api:window.FOXY_V12_PREVIEW,events,windowEvents,cards,writes,location,health,notice,more,click(dataset){const target=element(dataset);target.closest=()=>target;events.click?.({target,preventDefault(){}})}};
}
test('generated market card action routes and applies the market filter',()=>{const env=boot();env.click({route:'RESEARCH',market:'TW'});assert.equal(env.api.getState().route,'RESEARCH');assert.equal(env.api.getState().context,'TW');assert.equal(env.cards.find(x=>x.dataset.filterMarket==='US').hidden,true);assert.equal(env.cards.find(x=>x.dataset.filterMarket==='TW').hidden,false)});
test('market scope filters content, rejects invalid scopes, and restores All',()=>{const env=boot();env.api.setContext('US');assert.deepEqual(env.cards.map(x=>x.hidden),[false,true,true]);env.api.setContext('NOT_REAL');assert.equal(env.api.getState().context,'US');env.api.setContext('ALL');assert.deepEqual(env.cards.map(x=>x.hidden),[false,false,false])});
test('navigation records history and browser back restores the displayed screen and scope',()=>{const env=boot();env.api.setRoute('RESEARCH');assert.ok(env.writes.some(x=>x.kind==='push'&&x.url.startsWith('#research')));env.location.hash='#markets?market=TW';assert.equal(typeof env.windowEvents.hashchange,'function');env.windowEvents.hashchange();assert.equal(env.api.getState().route,'MARKETS');assert.equal(env.api.getState().context,'TW')});
test('unimplemented static actions and event filters are explicitly disabled with reasons',()=>{const tags=[...html.matchAll(/<button\b[^>]*>/g)].map(x=>x[0]);const placeholders=tags.filter(x=>/data-action=/.test(x));assert.ok(placeholders.length>0);for(const tag of placeholders){assert.match(tag,/\bdisabled\b/);assert.match(tag,/title="[^"]+"/)}for(const route of ['POSITIONS','RESULTS','LAB'])for(const tag of tags.filter(x=>x.includes(`data-route="${route}"`)))assert.match(tag,/\bdisabled\b/);const risks=html.split('id="risk-events"')[1].split('</section>')[0];for(const tag of risks.match(/<button\b[^>]*class="filter[^>]*>/g)||[])assert.match(tag,/disabled/)});
test('mobile has an accessible market selector outside the hidden sidebar',()=>{const rest=html.split('</aside>')[1];assert.match(rest,/aria-label="手機市場範圍"/);assert.match(rest,/data-context="TW"/)});
test('failed initial load provides persistent reason and retry feedback',async()=>{const env=boot({load:async()=>{throw Error('STAGING_READ_FAILED:500')}});await env.api.loadStagingHome();assert.match(env.notice.textContent,/500/);assert.match(env.notice.textContent,/重新/);assert.match(env.health.textContent,/資料不可用/)});
test('more menu closes with Escape',()=>{const env=boot();env.api.setRoute('MORE');assert.equal(env.more.hidden,false);assert.equal(typeof env.events.keydown,'function');env.events.keydown({key:'Escape'});assert.equal(env.more.hidden,true)});

test('idle snapshots become stale on navigation without requiring another network response',async()=>{let now=100;const env=boot({now:()=>now,load:async()=>({status:'AVAILABLE',data:{asOf:100,researchOnly:true,executionWrite:false}})});await env.api.loadStagingHome();now+=66*60*1000;env.api.setRoute('RESEARCH');assert.match(env.health.textContent,/快照過期/);assert.match(env.notice.textContent,/65/)});
test('initial pulse cards support scope even before Home becomes available',()=>{for(const tag of html.match(/<article[^>]*data-market-pulse[^>]*>/g)||[])assert.match(tag,/data-filter-market/)});
test('stale navigation preserves a failed refresh reason and an in-flight read notice',async()=>{let now=100,next=async()=>({status:'AVAILABLE',data:{asOf:100}});const env=boot({now:()=>now,load:()=>next()});await env.api.loadStagingHome();now+=66*60*1000;next=async()=>{throw Error('READ_TIMEOUT')};await env.api.loadStagingHome();env.api.setRoute('RESEARCH');assert.match(env.notice.textContent,/READ_TIMEOUT/);let finish;next=()=>new Promise(resolve=>{finish=resolve});const pending=env.api.loadStagingHome();env.api.setContext('TW');assert.match(env.notice.textContent,/正在讀取/);finish({status:'UNAVAILABLE',reason:'NO_DATA'});await pending});
test('initial opportunity cards filter by market before the first successful read',()=>{const cards=html.match(/<article[^>]*class="opportunity-card"[^>]*>/g)||[];assert.equal(cards.length,3);for(const tag of cards)assert.match(tag,/data-filter-market="(?:CRYPTO|US|TW)"/)});
