const test=require('node:test');
const assert=require('node:assert/strict');
const B=require('../v12/early_trend/evidence_builders.js');
const obs=(field,value,{status='SNAPSHOT',confidence=1,receivedAt=1000,source='official'}={})=>({field,value,status,confidence,receivedAt,observedAt:receivedAt-10,source});

test('institutional evidence scales net flow by traded volume with explicit materiality threshold',()=>{const e=B.buildInstitutionalFlowEvidence({instrumentId:'TWSE:2330',flowObservations:[obs('flow.foreign_net',200),obs('flow.investment_trust_net',50),obs('flow.dealer_net',50),obs('flow.total_net',300)],volumeObservation:obs('volume.shares',10000,{receivedAt:1010,source:'TWSE:STOCK_DAY_ALL'}),fullScaleRatio:0.05});assert.equal(e.family,'INSTITUTIONAL');assert.equal(e.kind,'INSTITUTIONAL_NET_VOLUME_RATIO');assert.equal(e.direction,0.6);assert.equal(e.status,'SNAPSHOT');assert.equal(e.asOf,1010);assert.equal(e.metrics.netToVolumeRatio,0.03);assert.equal(e.metrics.netShares,300);});
test('institutional evidence does not double-count total plus component flows',()=>{const e=B.buildInstitutionalFlowEvidence({instrumentId:'TWSE:2330',flowObservations:[obs('flow.foreign_net',200),obs('flow.investment_trust_net',50),obs('flow.dealer_net',50),obs('flow.total_net',300)],volumeObservation:obs('volume.shares',10000),fullScaleRatio:0.05});assert.equal(e.metrics.netShares,300);});
test('institutional evidence is unavailable without valid volume',()=>{const e=B.buildInstitutionalFlowEvidence({instrumentId:'TWSE:2330',flowObservations:[obs('flow.total_net',300)],volumeObservation:obs('volume.shares',null),fullScaleRatio:0.05});assert.equal(e.status,'UNAVAILABLE');assert.equal(e.confidence,0);assert.equal(e.direction,0);});
test('institutional evidence requires explicit positive materiality scale',()=>{assert.throws(()=>B.buildInstitutionalFlowEvidence({instrumentId:'TWSE:2330',flowObservations:[],volumeObservation:obs('volume.shares',10000)}),/FULL_SCALE_RATIO_REQUIRED/);});
test('management guidance revision becomes EXPECTATION evidence without claiming analyst consensus',()=>{const previous={instrument:{instrumentId:'TSE:72030'},disclosedAt:1000,pointInTimeSafe:true,observations:[obs('guidance.sales_fy',100,{receivedAt:1000}),obs('guidance.operating_profit_fy',20,{receivedAt:1000}),obs('guidance.net_profit_fy',10,{receivedAt:1000}),obs('guidance.eps_fy',5,{receivedAt:1000})]};const current={instrument:{instrumentId:'TSE:72030'},disclosedAt:2000,pointInTimeSafe:true,observations:[obs('guidance.sales_fy',110,{receivedAt:2000}),obs('guidance.operating_profit_fy',24,{receivedAt:2000}),obs('guidance.net_profit_fy',11,{receivedAt:2000}),obs('guidance.eps_fy',5.5,{receivedAt:2000})]};const e=B.buildGuidanceRevisionEvidence({current,previous,fullScalePct:20});assert.equal(e.family,'EXPECTATION');assert.equal(e.kind,'MANAGEMENT_GUIDANCE_REVISION');assert.equal(e.direction,0.625);assert.equal(e.asOf,2000);assert.equal(e.metrics.usableFields,4);assert.equal(Object.hasOwn(e.metrics,'analystConsensus'),false);});
test('guidance revision is unavailable when disclosure timing is not point-in-time safe',()=>{const previous={instrument:{instrumentId:'TSE:72030'},disclosedAt:null,pointInTimeSafe:false,observations:[]};const current={instrument:{instrumentId:'TSE:72030'},disclosedAt:2000,pointInTimeSafe:true,observations:[]};const e=B.buildGuidanceRevisionEvidence({current,previous,fullScalePct:20});assert.equal(e.status,'UNAVAILABLE');});
test('guidance revision excludes cross-zero fields instead of producing explosive percent change',()=>{const previous={instrument:{instrumentId:'TSE:72030'},disclosedAt:1000,pointInTimeSafe:true,observations:[obs('guidance.sales_fy',100,{receivedAt:1000}),obs('guidance.net_profit_fy',-10,{receivedAt:1000})]};const current={instrument:{instrumentId:'TSE:72030'},disclosedAt:2000,pointInTimeSafe:true,observations:[obs('guidance.sales_fy',110,{receivedAt:2000}),obs('guidance.net_profit_fy',10,{receivedAt:2000})]};const e=B.buildGuidanceRevisionEvidence({current,previous,fullScalePct:20});assert.deepEqual(e.metrics.crossZeroFields,['guidance.net_profit_fy']);assert.equal(e.metrics.usableFields,1);assert.equal(e.direction,0.5);});
