const test=require('node:test');
const assert=require('node:assert/strict');
const B=require('../v12/early_trend/evidence_builders.js');
const obs=(field,value,{status='SNAPSHOT',confidence=1,receivedAt=1000,source='official'}={})=>({field,value,status,confidence,receivedAt,observedAt:receivedAt-10,source});
const session=(net,volume,receivedAt)=>({flowObservations:[obs('flow.total_net',net,{receivedAt,source:'TWSE:T86'})],volumeObservation:obs('volume.shares',volume,{receivedAt,source:'TWSE:STOCK_DAY_ALL'})});
const revenue=(period,yoy,receivedAt)=>({instrument:{instrumentId:'TWSE:2330'},reportPeriod:period,knowledgeTime:'RECEIVED_AT',observations:[obs('fundamental.revenue.yoy_pct',yoy,{receivedAt,source:'TWSE:t187ap05_L'})]});

test('institutional persistence rewards repeated net buying rather than one-day flow',()=>{const e=B.buildInstitutionalPersistenceEvidence({instrumentId:'TWSE:2330',sessions:[session(200,10000,1000),session(300,10000,2000),session(400,10000,3000)],minSessions:3,fullScaleAverageRatio:0.05});assert.equal(e.family,'INSTITUTIONAL');assert.equal(e.kind,'INSTITUTIONAL_PERSISTENCE');assert.equal(e.direction,0.6);assert.equal(e.metrics.averageNetToVolumeRatio,0.03);assert.equal(e.metrics.positiveSessions,3);assert.equal(e.metrics.usableSessions,3);assert.equal(e.asOf,3000);});
test('institutional persistence confidence falls when sessions disagree',()=>{const consistent=B.buildInstitutionalPersistenceEvidence({instrumentId:'TWSE:2330',sessions:[session(200,10000,1000),session(300,10000,2000),session(400,10000,3000)],minSessions:3,fullScaleAverageRatio:0.05});const mixed=B.buildInstitutionalPersistenceEvidence({instrumentId:'TWSE:2330',sessions:[session(200,10000,1000),session(300,10000,2000),session(-100,10000,3000)],minSessions:3,fullScaleAverageRatio:0.05});assert.ok(mixed.confidence<consistent.confidence);assert.equal(mixed.metrics.negativeSessions,1);});
test('institutional persistence is unavailable when too few valid sessions remain',()=>{const e=B.buildInstitutionalPersistenceEvidence({instrumentId:'TWSE:2330',sessions:[session(200,10000,1000),session(300,null,2000)],minSessions:2,fullScaleAverageRatio:0.05});assert.equal(e.status,'UNAVAILABLE');assert.equal(e.direction,0);assert.equal(e.metrics.usableSessions,1);});
test('institutional persistence requires explicit session and materiality parameters',()=>{assert.throws(()=>B.buildInstitutionalPersistenceEvidence({instrumentId:'TWSE:2330',sessions:[]}),/MIN_SESSIONS_REQUIRED|FULL_SCALE_AVERAGE_RATIO_REQUIRED/);});
test('monthly revenue YoY acceleration becomes expectation evidence using received knowledge time',()=>{const e=B.buildRevenueAccelerationEvidence({current:revenue('2026-08',20,3000),previous:revenue('2026-07',8,2000),fullScalePct:20});assert.equal(e.family,'EXPECTATION');assert.equal(e.kind,'MONTHLY_REVENUE_YOY_ACCELERATION');assert.equal(e.direction,0.6);assert.equal(e.metrics.currentYoYPct,20);assert.equal(e.metrics.previousYoYPct,8);assert.equal(e.metrics.accelerationPctPoints,12);assert.equal(e.asOf,3000);});
test('monthly revenue acceleration works across zero without ratio explosion',()=>{const e=B.buildRevenueAccelerationEvidence({current:revenue('2026-08',5,3000),previous:revenue('2026-07',-5,2000),fullScalePct:20});assert.equal(e.metrics.accelerationPctPoints,10);assert.equal(e.direction,0.5);});
test('monthly revenue acceleration rejects non-forward or mismatched series',()=>{const samePeriod=B.buildRevenueAccelerationEvidence({current:revenue('2026-07',20,3000),previous:revenue('2026-07',8,2000),fullScalePct:20});assert.equal(samePeriod.status,'UNAVAILABLE');const other=revenue('2026-08',20,3000);other.instrument={instrumentId:'TWSE:2317'};const mismatch=B.buildRevenueAccelerationEvidence({current:other,previous:revenue('2026-07',8,2000),fullScalePct:20});assert.equal(mismatch.status,'UNAVAILABLE');});
test('monthly revenue acceleration requires explicit materiality scale',()=>{assert.throws(()=>B.buildRevenueAccelerationEvidence({current:revenue('2026-08',20,3000),previous:revenue('2026-07',8,2000)}),/FULL_SCALE_PCT_REQUIRED/);});
